### ISSUE TITLE
1.0.1+1.20.1 is targetting 1.20.2+

### ISSUE THREAD

**Issue by No3371** [axialeaa/SimpleHollowLogs#1]
> Mod 'Axia's Simple Hollow Logs' (simple-hollow-logs) 1.0.1+1.20.1 requires any version between 1.20.2 (inclusive) and 1.21- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!

**Comment by axialeaa** [comment]
Thanks for reporting. I know what causes this issue, but I don't really know what to do about it, since I set up my local files in a way that fails to accommodate editing older versions of my mods. However, this bug does create misleading behaviour and will surely confuse some users like yourself.

I may change the release names to reflect its 1.20.2-only restriction and remember the mistake I made in order to prevent it happening in the future. Not the answer I was hoping to give. Sorry for the inconvenience :/
